Repository qonto/ember-prismic-dom, pull requests merged in 2023-11, with the labels that each got.

#86 feat(dev-deps): remove ember-data
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#88 refactor: use variable assignment and bound value instead of {{component}} helper
  ember-prismic-dom/src/components/prismic/element.hbs
Labels: enhancement

#89 feat: setup TypeScript
  .gitignore
  ember-prismic-dom/.eslintignore
  ember-prismic-dom/.eslintrc.cjs
  ember-prismic-dom/.prettierignore
  ember-prismic-dom/babel.config.json
  ember-prismic-dom/package.json
  ember-prismic-dom/rollup.config.mjs
  ember-prismic-dom/src/components/prismic/children.hbs
  ember-prismic-dom/src/components/prismic/dom.hbs
  ember-prismic-dom/src/components/prismic/element.hbs
  ember-prismic-dom/src/components/prismic/image.hbs
  ember-prismic-dom/src/unpublished-development-types/index.d.ts
  ember-prismic-dom/tsconfig.json
  pnpm-lock.yaml
  test-app/.eslintrc.js
  test-app/app/config/environment.d.ts
  test-app/package.json
  test-app/tsconfig.json
  test-app/types/glint.d.ts
  test-app/types/test-app/index.d.ts
Labels: internal

#87 chore(deps-dev): update test-app to ember-source@5.3.0
  .github/workflows/ci.yml
  ember-prismic-dom/package.json
  pnpm-lock.yaml
  test-app/config/ember-try.js
  test-app/package.json
Labels: dependencies

#115 feat: drop node v16
  .github/workflows/ci.yml
  README.md
  package.json
  test-app/package.json
Labels: breaking

#116 refactor: migrate addon package to TypeScript
  .github/workflows/ci.yml
  README.md
  ember-prismic-dom/package.json
  ember-prismic-dom/rollup.config.mjs
  ember-prismic-dom/src/components/prismic/children.hbs
  ember-prismic-dom/src/components/prismic/children.ts
  ember-prismic-dom/src/components/prismic/dom.hbs
  ember-prismic-dom/src/components/prismic/dom.js
  ember-prismic-dom/src/components/prismic/dom.ts
  ember-prismic-dom/src/components/prismic/element.hbs
  ember-prismic-dom/src/components/prismic/element.js
  ember-prismic-dom/src/components/prismic/element.ts
  ember-prismic-dom/src/components/prismic/image.hbs
  ember-prismic-dom/src/components/prismic/image.ts
  ember-prismic-dom/src/helpers/eq.js
  ember-prismic-dom/src/template-registry.ts
  ember-prismic-dom/src/unpublished-development-types/index.d.ts
  ember-prismic-dom/tsconfig.json
  package.json
  pnpm-lock.yaml
  test-app/tests/integration/helpers/eq-test.js
Labels: enhancement

#132 refactor: migrate test app package to TypeScript
  .github/workflows/ci.yml
  test-app/app/app.ts
  test-app/app/components/group-list-item.hbs
  test-app/app/components/group-list-item.ts
  test-app/app/components/hyperlink.hbs
  test-app/app/components/hyperlink.ts
  test-app/app/components/list-item.hbs
  test-app/app/components/list-item.ts
  test-app/app/components/super-custom.hbs
  test-app/app/components/super-custom.ts
  test-app/app/router.ts
  test-app/config/ember-try.js
  test-app/package.json
  test-app/tests/helpers/clean-html.js
  test-app/tests/helpers/clean-html.ts
  test-app/tests/helpers/index.ts
  test-app/tests/integration/components/prismic/dom-test.ts
  test-app/tests/integration/components/prismic/element-test.ts
  test-app/tests/integration/components/prismic/image-test.ts
  test-app/types/glint.d.ts
Labels: enhancement
